#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
  - name: Check we are running in the directory of the script
    debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/osx_ansible')

- hosts: localhost
  connection: local
  roles:
  - vim
  - homebrew
  - monome-crow
