---
# tasks file for cli-tools

# ranger directory navigator
- name: install ranger
  homebrew:
    name: ranger
    state: present

- name: install modern cli tools
  homebrew:
    name: "{{ modern_cli_tools }}"
    state: present