---
# tasks file for emacs

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true

- name: Tap
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: install nerd fonts
  community.general.homebrew_cask:
    name: font-hack-nerd-font
    state: present
    
- name: install emacs
  community.general.homebrew_cask:
    name: emacs
    state: present
    install_options: force

# -------------------------------------------------------------------------------
# Create directories
# -------------------------------------------------------------------------------

- name: create org directory
  ansible.builtin.file:
    path: ~/org
    state: directory
    mode: '0755'

- name: create org agenda directory
  ansible.builtin.file:
    path: ~/org/agenda
    state: directory
    mode: '0755'

- name: create nested org-roam directory
  ansible.builtin.file:
    path: ~/org/roam
    state: directory
    mode: '0755'

- name: create org-roam inbox directory
  ansible.builtin.file:
    path: ~/org/roam/inbox
    state: directory
    mode: '0755'

- name: create org-roam directory
  ansible.builtin.file:
    path: ~/org-roam
    state: directory
    mode: '0755'

# -------------------------------------------------------------------------------
# Install pdf-tools dependencies
# -------------------------------------------------------------------------------

- name: install poppler
  homebrew:
    name: poppler
    state: present

- name: install automake
  homebrew:
    name: automake
    state: present

- name: install zlib
  homebrew:
    name: zlib
    state: present

- name: install expat
  homebrew:
    name: expat
    state: present

# -------------------------------------------------------------------------------
# Install dirvish dependencies
# -------------------------------------------------------------------------------

- name: install fd
  homebrew:
    name: fd
    state: present

# dirvish will complain about ls without this
- name: install coreutils
  homebrew:
    name: coreutils
    state: present

# -------------------------------------------------------------------------------
# Install ripgrep
# -------------------------------------------------------------------------------

- name: install ripgrep
  homebrew:
    name: ripgrep
    state: present

# -------------------------------------------------------------------------------
# Install python tools
# -------------------------------------------------------------------------------

- name: install autopep8 for python development
  ansible.builtin.pip:
    name: autopep8

# fails if not run as root?
- name: install puppet-lint
  community.general.gem:
    name: puppet-lint
    state: present

# -------------------------------------------------------------------------------
# Install gpg
# -------------------------------------------------------------------------------

- name: install gpg
  homebrew:
    name: gpg
    state: present

# -------------------------------------------------------------------------------
# Install tree-sitter libraries
# -------------------------------------------------------------------------------

- name: install tree-sitter-yaml
  #become: true
  community.general.npm:
    name: tree-sitter-yaml
    #path: /usr/local/lib
    global: true
 
