---
# tasks file for emacs

- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true

- name: install emacs
  community.general.homebrew_cask:
    name: emacs
    state: present
    install_options: force

# fd is used by dirvish
- name: install fd
  homebrew:
    name: fd
    state: present

- name: install autopep8 for python development
  ansible.builtin.pip:
    name: autopep8

# fails if not run as root?
- name: install puppet-lint
  community.general.gem:
    name: puppet-lint
    state: present
